-- AlterTable
ALTER TABLE "scores" ALTER COLUMN "ecc1_explanation" DROP NOT NULL,
ALTER COLUMN "ecc1_explanation" DROP DEFAULT,
ALTER COLUMN "ecc2_explanation" DROP NOT NULL,
ALTER COLUMN "ecc2_explanation" DROP DEFAULT,
ALTER COLUMN "ecc3_explanation" DROP NOT NULL,
ALTER COLUMN "ecc3_explanation" DROP DEFAULT,
ALTER COLUMN "ecc4_explanation" DROP NOT NULL,
ALTER COLUMN "ecc4_explanation" DROP DEFAULT,
ALTER COLUMN "ecc5_explanation" DROP NOT NULL,
ALTER COLUMN "ecc5_explanation" DROP DEFAULT,
ALTER COLUMN "ere1_explanation" DROP NOT NULL,
ALTER COLUMN "ere1_explanation" DROP DEFAULT,
ALTER COLUMN "ere2_explanation" DROP NOT NULL,
ALTER COLUMN "ere2_explanation" DROP DEFAULT,
ALTER COLUMN "ere3_explanation" DROP NOT NULL,
ALTER COLUMN "ere3_explanation" DROP DEFAULT,
ALTER COLUMN "ere4_explanation" DROP NOT NULL,
ALTER COLUMN "ere4_explanation" DROP DEFAULT,
ALTER COLUMN "ere5_explanation" DROP NOT NULL,
ALTER COLUMN "ere5_explanation" DROP DEFAULT,
ALTER COLUMN "gpm1_explanation" DROP NOT NULL,
ALTER COLUMN "gpm1_explanation" DROP DEFAULT,
ALTER COLUMN "gpm2_explanation" DROP NOT NULL,
ALTER COLUMN "gpm2_explanation" DROP DEFAULT,
ALTER COLUMN "gpm3_explanation" DROP NOT NULL,
ALTER COLUMN "gpm3_explanation" DROP DEFAULT,
ALTER COLUMN "hwq1_explanation" DROP NOT NULL,
ALTER COLUMN "hwq1_explanation" DROP DEFAULT,
ALTER COLUMN "hwq2_explanation" DROP NOT NULL,
ALTER COLUMN "hwq2_explanation" DROP DEFAULT,
ALTER COLUMN "hwq3_explanation" DROP NOT NULL,
ALTER COLUMN "hwq3_explanation" DROP DEFAULT,
ALTER COLUMN "ilp1_explanation" DROP NOT NULL,
ALTER COLUMN "ilp1_explanation" DROP DEFAULT,
ALTER COLUMN "ilp2_explanation" DROP NOT NULL,
ALTER COLUMN "ilp2_explanation" DROP DEFAULT,
ALTER COLUMN "sti1_explanation" DROP NOT NULL,
ALTER COLUMN "sti1_explanation" DROP DEFAULT,
ALTER COLUMN "sti2_explanation" DROP NOT NULL,
ALTER COLUMN "sti2_explanation" DROP DEFAULT,
ALTER COLUMN "sti3_explanation" DROP NOT NULL,
ALTER COLUMN "sti3_explanation" DROP DEFAULT,
ALTER COLUMN "sti4_explanation" DROP NOT NULL,
ALTER COLUMN "sti4_explanation" DROP DEFAULT,
ALTER COLUMN "wmr1_explanation" DROP NOT NULL,
ALTER COLUMN "wmr1_explanation" DROP DEFAULT,
ALTER COLUMN "wmr2_explanation" DROP NOT NULL,
ALTER COLUMN "wmr2_explanation" DROP DEFAULT,
ALTER COLUMN "wmr3_explanation" DROP NOT NULL,
ALTER COLUMN "wmr3_explanation" DROP DEFAULT,
ALTER COLUMN "wmr4_explanation" DROP NOT NULL,
ALTER COLUMN "wmr4_explanation" DROP DEFAULT,
ALTER COLUMN "wmr5_explanation" DROP NOT NULL,
ALTER COLUMN "wmr5_explanation" DROP DEFAULT;

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "email_verification_token" TEXT,
ADD COLUMN     "email_verification_token_expires" TIMESTAMP(3),
ADD COLUMN     "email_verified" BOOLEAN NOT NULL DEFAULT false;
