-- AlterTable
ALTER TABLE "scores" ADD COLUMN     "ecc1_explanation" TEXT,
ADD COLUMN     "ecc2_explanation" TEXT,
ADD COLUMN     "ecc3_explanation" TEXT,
ADD COLUMN     "ecc4_explanation" TEXT,
ADD COLUMN     "ecc5_explanation" TEXT,
ADD COLUMN     "ere1_explanation" TEXT,
ADD COLUMN     "ere2_explanation" TEXT,
ADD COLUMN     "ere3_explanation" TEXT,
ADD COLUMN     "ere4_explanation" TEXT,
ADD COLUMN     "ere5_explanation" TEXT,
ADD COLUMN     "gpm1_explanation" TEXT,
ADD COLUMN     "gpm2_explanation" TEXT,
ADD COLUMN     "gpm3_explanation" TEXT,
ADD COLUMN     "hwq1_explanation" TEXT,
ADD COLUMN     "hwq2_explanation" TEXT,
ADD COLUMN     "hwq3_explanation" TEXT,
ADD COLUMN     "ilp1_explanation" TEXT,
ADD COLUMN     "ilp2_explanation" TEXT,
ADD COLUMN     "sti1_explanation" TEXT,
ADD COLUMN     "sti2_explanation" TEXT,
ADD COLUMN     "sti3_explanation" TEXT,
ADD COLUMN     "sti4_explanation" TEXT,
ADD COLUMN     "wmr1_explanation" TEXT,
ADD COLUMN     "wmr2_explanation" TEXT,
ADD COLUMN     "wmr3_explanation" TEXT,
ADD COLUMN     "wmr4_explanation" TEXT,
ADD COLUMN     "wmr5_explanation" TEXT;
