-- AlterTable
ALTER TABLE "schools" ADD COLUMN     "status" TEXT NOT NULL DEFAULT 'pending',
ADD COLUMN     "verified_at" TIMESTAMP(3),
ALTER COLUMN "total_score" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "scores" ALTER COLUMN "sti1" SET DEFAULT 0,
ALTER COLUMN "sti1" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "sti2" SET DEFAULT 0,
ALTER COLUMN "sti2" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "sti3" SET DEFAULT 0,
ALTER COLUMN "sti3" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "sti4" SET DEFAULT 0,
ALTER COLUMN "sti4" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "wmr1" SET DEFAULT 0,
ALTER COLUMN "wmr1" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "wmr2" SET DEFAULT 0,
ALTER COLUMN "wmr2" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "wmr3" SET DEFAULT 0,
ALTER COLUMN "wmr3" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "wmr4" SET DEFAULT 0,
ALTER COLUMN "wmr4" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "wmr5" SET DEFAULT 0,
ALTER COLUMN "wmr5" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "ecc1" SET DEFAULT 0,
ALTER COLUMN "ecc1" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "ecc2" SET DEFAULT 0,
ALTER COLUMN "ecc2" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "ecc3" SET DEFAULT 0,
ALTER COLUMN "ecc3" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "ecc4" SET DEFAULT 0,
ALTER COLUMN "ecc4" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "ecc5" SET DEFAULT 0,
ALTER COLUMN "ecc5" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "hwq1" SET DEFAULT 0,
ALTER COLUMN "hwq1" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "hwq2" SET DEFAULT 0,
ALTER COLUMN "hwq2" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "hwq3" SET DEFAULT 0,
ALTER COLUMN "hwq3" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "gpm1" SET DEFAULT 0,
ALTER COLUMN "gpm1" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "gpm2" SET DEFAULT 0,
ALTER COLUMN "gpm2" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "gpm3" SET DEFAULT 0,
ALTER COLUMN "gpm3" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "ilp1" SET DEFAULT 0,
ALTER COLUMN "ilp1" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "ilp2" SET DEFAULT 0,
ALTER COLUMN "ilp2" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "ere1" SET DEFAULT 0,
ALTER COLUMN "ere1" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "ere2" SET DEFAULT 0,
ALTER COLUMN "ere2" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "ere3" SET DEFAULT 0,
ALTER COLUMN "ere3" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "ere4" SET DEFAULT 0,
ALTER COLUMN "ere4" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "ere5" SET DEFAULT 0,
ALTER COLUMN "ere5" SET DATA TYPE DOUBLE PRECISION;

-- CreateTable
CREATE TABLE "admins" (
    "id" TEXT NOT NULL,
    "username" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "admins_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "admins_username_key" ON "admins"("username");
